### ISSUE TITLE
components and groups are not created

### ISSUE THREAD

**Issue by sentinel159868** [qk4l/zabbix-cachet#10]
Hi Alex,

another problem. Ich can see, in debug mode, that i get an response from my zabbix-server. but nothing is happened on cachet side. Responses for child items are empty...

Any hint for that?
Zabbix: 3.0.7
Cachet: 2.3.9
Api are both working.
User have the rights.

Debug output on zabbix-server:

2017-01-22 16:16:44 CET INFO: (MainThread) Zabbix Cachet v.0.1 started
2017-01-22 16:16:44 CET INFO: (MainThread) JSON-RPC Server Endpoint: http://watchdog01.test.int/api_jsonrpc.php
2017-01-22 16:16:44 CET DEBUG: (MainThread) Sending: {
    "id": 0,
    "params": {
        "user": "user_cachet",
        "password": "XXX"
    },
    "jsonrpc": "2.0",
    "method": "user.login"
}
2017-01-22 16:16:44 CET DEBUG: (MainThread) Response Code: 200
2017-01-22 16:16:44 CET DEBUG: (MainThread) Response Body: {
    "id": 0,
    "result": "933cd00b59683575aeedb096318fb11e",
    "jsonrpc": "2.0"
}
2017-01-22 16:16:44 CET DEBUG: (MainThread) Sending: {
    "auth": "933cd00b59683575aeedb096318fb11e",
    "id": 1,
    "params": {
        "filter": {
            "name": "cachet_status"
        },
        "selectDependencies": "extend"
    },
    "jsonrpc": "2.0",
    "method": "service.get"
}
2017-01-22 16:16:44 CET DEBUG: (MainThread) Response Code: 200
2017-01-22 16:16:44 CET DEBUG: (MainThread) Response Body: {
    "id": 1,
    "result": [
        {
            "triggerid": "0",
            "serviceid": "6",
            "goodsla": "99.0500",
            "name": "XXXXX_status",
            "dependencies": [],
            "sortorder": "0",
            "showsla": "1",
            "status": "1",
            "algorithm": "1"
        }
    ],
    "jsonrpc": "2.0"
}
2017-01-22 16:16:44 CET DEBUG: (MainThread) Sending: {
    "auth": "933cd00b59683575aeedb096318fb11e",
    "id": 2,
    "params": {
        "serviceids": [],
        "selectDependencies": "extend"
    },
    "jsonrpc": "2.0",
    "method": "service.get"
}
2017-01-22 16:16:44 CET DEBUG: (MainThread) Response Code: 200
2017-01-22 16:16:44 CET DEBUG: (MainThread) Response Body: {
    "id": 2,
    "result": [],
    "jsonrpc": "2.0"
}

thanks in advance and regards
sentinel

**Comment by qk4l** [comment]
Hello, @sentinel159868 ,

As I see you do not have any child (depended) service under your _root_service_ - _cachet_status_.

_root_service_   in config file provide option to filter out other Zabbix service which should not be sync to Cachet. This service just a point from which Zabbix-Cachet should start.

Try to create a new service under _cachet_status_ and assign trigger to it.

Here is working tree:
_Cachet_  -  _root_service_
_Bitbucket_ - service without trigger - group Name
_Git https -Example Trigger_ - serice with assign trigger - item Name

https://cloud.githubusercontent.com/assets/8394059/14297272/0b79bc1a-fb8f-11e5-820f-5460cc735cda.png

**Comment by sentinel159868** [comment]
Hi Alex,

thanks for your answer, but i've created childs under the root "startpoint" cachet_status. Your script is seeing the root node - but not the subordinated childs..... (Sorry for the above example - cachet_status is the same as XXXXX_status)

New run of zabbix_chachet.py:

2017-01-30 18:51:48 CET DEBUG: (MainThread) Response Body: {
    "result": [
        {
            "triggerid": "0",
            "sortorder": "0",
            "algorithm": "1",
            "status": "0",
            "name": "XXXXXX_status",
            "showsla": "1",
            "dependencies": [],
            "goodsla": "99.0500",
            "serviceid": "6"
        }
    ],
    "jsonrpc": "2.0",
    "id": 27
}
2017-01-30 18:51:48 CET DEBUG: (MainThread) Sending: {
    "auth": "68f0368b3b0dd1a3e9a3f48a711d12c7",
    "jsonrpc": "2.0",
    "id": 28,
    **"params": {
        "serviceids": [],
        "selectDependencies": "extend"
    },**
    "method": "service.get"
}


![image](https://cloud.githubusercontent.com/assets/22539551/22434442/5908036e-e71c-11e6-8147-9fa2c0f56829.png)

regards
sentinel

**Comment by qk4l** [comment]
It's strange.

Zabbix does not return _dependencies_ for root service (XXXXXX_status) as a result next request does not have any _serviceids_ in params.

```
{
"triggerid": "0",
"sortorder": "0",
"algorithm": "1",
"status": "0",
"name": "XXXXXX_status",
"showsla": "1",
"dependencies": [],  < empty
"goodsla": "99.0500",
"serviceid": "6"
}
```

**Comment by sentinel159868** [comment]
Hmmm Ok..... but the dependencies are available. See the screenshot......

![image](https://cloud.githubusercontent.com/assets/22539551/22436488/9962450c-e724-11e6-9615-d18c7535c9d9.png)

**Comment by qk4l** [comment]
I've added some human logging to zabbix-cachet v.0.2 hopes it helps you to find what wrong in your installation. May be you have more than one IT Service with same name?

Also I've tested zabbix-cachet with Zabbix 3.2.3 and Cachet 2.3.9 - no problem.

**Comment by sentinel159868** [comment]
I will test it an report it back to you. Many thanks for your help!!!!!
