### ISSUE TITLE
Ability to nest trigers

### ISSUE THREAD

**Issue by dbnewman** [qk4l/zabbix-cachet#12]
Hi Artem,

Would it be possible to add the ability to trigger a service based on its subordinate triggers?

Currently only one level of nesting is allowed, we would like to have high-level categories that can be triggered by a number of subordinates.

ie.

Service Status (root level)
-- Core Services
---- Internet Service (shown on cachet, triggers based on subordinates)
------ Proxy Service (trigger, hidden on cachet)
------ DNS Service (trigger, hidden on cachet)

![capture](https://cloud.githubusercontent.com/assets/25624489/22716633/958934b2-ede2-11e6-9fd5-34228856071d.PNG)

**Comment by qk4l** [comment]
Hi,
I was in my todo list since beginning.

What do you think about Cachet incidents name/message in this scenario?

**Comment by dbnewman** [comment]
This is how I went about it, Zabbix calls this script each time a trigger is updated which in turn updates the component/incident. We are still using your script to sync the groups/components, I guess it would be nice to have it "all in one", are also only trigger one level deep below the component at this point.

![capture](https://cloud.githubusercontent.com/assets/25624489/23440849/76db0246-fe6a-11e6-9d6a-562196bdbe45.PNG)
[zabbix-cachet.zip](https://github.com/qk4l/zabbix-cachet/files/809386/zabbix-cachet.zip)

**Comment by networkdawg** [comment]
Just wondering if there was any update to this enhancement? I am trying to setup IT Services lower down, and even though the status is reported all the way up to the root, my cachet doesn't get updated.

**Comment by jensolsson** [comment]
@qk4l just tried the brqnch. It does indeed seem to work!

i created a tree like this:
Root
-Test
—Test Child
—-Leaf
——Trigger X

And when the trigger activated the fault would propagate all the way up to Test. 

Now I might have found a regression or a completely different fault. I later exchanged Trigger X with another Trigger Y and cachet does not see the change. 
test Leaf had this (?) symbol and holding over it still shows Trigger X even if I replaced it hours ago. 


Any plan on when this branch will make it into master?

kind regards
Jens
