### ISSUE TITLE
Duplicating components

### ISSUE THREAD

**Issue by GabrielRF** [qk4l/zabbix-cachet#13]
Everytime the container checks for new IT services my components are duplicated on Cachet. After a while it becomes a problem, overloading my server. 
Anyone else having the same issue? Any ideas?

**Comment by qk4l** [comment]
Hi,

Sounds strange. Is dubs components have same name?
Zabbix-cachet do not remove anything from Cachet. It only adds new components/groups.

**Comment by GabrielRF** [comment]
Yes. Everything doubled has the same name. Take a look at it:
![img](http://i.imgur.com/mR8Yr1R.png)
This one has 128 occurrences already.

**Comment by qk4l** [comment]
What version of Cachet do you use?
Could you attach a debug log of zabbix-cachet with information logs about  'Component Group' and 'Component {name}'  creating.

Thanks.

**Comment by GabrielRF** [comment]
Cachet v2.3.11

The log is huge! Should I look for something in particular? This is the last time it ran (it's stopped now) and duplicated components (one more time):
```
2017-06-10 20:28:18  INFO: (MainThread) Component rn.leg.br em dns1.infra.leg.br was created in group id 1162.
2017-06-10 20:28:18  INFO: (MainThread) Component rn.leg.br em dns2.infra.leg.br was created in group id 1162.
2017-06-10 20:28:18  INFO: (MainThread) Component Group mt.leg.br was created.
2017-06-10 20:28:19  INFO: (MainThread) Component mt.leg.br em dns2.infra.leg.br was created in group id 1163.
2017-06-10 20:28:19  INFO: (MainThread) Component mt.leg.br em dns1.infra.leg.br was created in group id 1163.
2017-06-10 20:28:19  INFO: (MainThread) Successfully synced Cachet components with Zabbix Services
2017-06-10 20:28:19  INFO: (MainThread) Restart triggers_watcher worker
```

**Comment by qk4l** [comment]
I have not reproduced exactly this case (as I understand it) but found some cases when duplicate components could be created.

Created the issue CachetHQ/Cachet#2598

Could you provide output for next command so I can check what Cachet returns.
  
```
   curl --request GET --url http(s)://{cachet_url}/api/v1/components
```

Thank you.

**Comment by GabrielRF** [comment]
Curl seems ok to me...
https://pastebin.com/0MkbmzW5

I'll try setting the `update_comp_interval` to 120 then.

**Comment by qk4l** [comment]
Wow! You have 4631 components. 
Because of that Cachet returns them in pages but _zabbix_cachet_ does not support it.

I'll fix it.

How many childs do you have in Zabbix under _leg.br_ service? 
If total number of components in Cachet less that 20 you should clean it (recreate) and problem will gone.
If you have more please wait for a fix.

**Comment by GabrielRF** [comment]
A have a little more than 20. I'll wait for your fix.
Thanks in advance.

**Comment by qk4l** [comment]
@GabrielRF , please try a new version 0.2.1 it should works well. 

You can clean your Cachet from all components and groups by [this](https://gist.github.com/qk4l/d11c1f87f332636f6cfcdaaf0892e2fe#file-clean-cachet-from-components) script or clean/recreate database by your properly way.

**Comment by GabrielRF** [comment]
I'll try it now! I'll let you know if it's ok asap! Thanks for everything.

**Comment by GabrielRF** [comment]
![image](http://i.imgur.com/oNwDPFz.png)
The problem continues here..

**Comment by GabrielRF** [comment]
@qk4l Problem solved! Once again, thank you!
