### ISSUE TITLE
Using only IT Services from Zabbix?

### ISSUE THREAD

**Issue by nan008** [qk4l/zabbix-cachet#14]
Hi, 

I started evaluating Cachet for our system. I have Zabbix implemented and monitoring - trying to integrate it with Cachet and on their website they are recommend zabbix-cachet plugin as 3rd party integration solution. I would like to send web scenerios status to Cachet will this plugin allow me to do that?

**Comment by qk4l** [comment]
Hi,

Yes of course.

Create web_monitoring item and trigger for it.
Then create [IT Service](https://www.zabbix.com/documentation/3.4/manual/it_services) and link it to your trigger.

Zabbix-cachet do not care about trigger`s type. You can use anyone.
I implemented zabbix-cachet integration via  IT Services because there is a separate interface for this in Zabbix where user can easily collect triggers which he/she want to share.

**Comment by nan008** [comment]
Ok, I started the implementation but then got this error

('Error -32602: Invalid params., Incorrect method "user.authenticate". while sending {\'params\': {\'password\': \'zabbix\', \'user\': \'admin\'}, \'jsonrpc\': \'2.0\', \'method\': \'user.authenticate\', \'id\': \'1\'}', -32602)

Running Zabbix 3.2.6
OS Centos 7

Do I need admin account? I am login as me as I have Super admin status on Zabbix.

The problem for me is the config.yml - should I use urls in the servers places

```bash
zabbix:
  user: anna
  pass: password123
  server: https://zabbix.example.com/
  https-verify: true

cachet:
  token: ZMOaSufBTkM0
  server: https://status.cachet.com/
  https-verify: true

settings:
  # IT Service which will be a root for Cachet Components
  # Leave it empty if you want to use /
  root_service: ''
  # How often check Zabbix for new incidents
  update_inc_interval: 120  # in seconds
  # How often check Zabbix for new IT Services
  update_comp_interval: 3600  # in seconds
  # Log level https://docs.python.org/3.4/library/logging.html#levels
  log_level: INFO
  # Additional logging level for requests module
  log_level_requests: WARNING
```

I have Web scenario and connected trigger to it - when it is down longer then 5 m on zabbix, trigger will go off - I tested it and it is working

![screen shot 2017-07-20 at 10 25 51](https://user-images.githubusercontent.com/18073067/28410602-1129719a-6d36-11e7-85e7-2f4f6b32cc55.png)
