### ISSUE TITLE
Triggers not updating status after Zabbix is triggering events

### ISSUE THREAD

**Issue by nan008** [qk4l/zabbix-cachet#18]
So I managed the get zabbix-cachet plugin working. Now I have another issue (or issues)

First plugin is checking the status of the triggers every 60 minutes which is reflected in the log

```bash
Aug  3 08:49:56 localhost python: 2017-08-03 08:49:56 UTC INFO: (MainThread) Successfully synced Cachet components with Zabbix Services
Aug  3 09:49:57 localhost python: 2017-08-03 09:49:57 UTC INFO: (MainThread) Successfully synced Cachet components with Zabbix Services
```

Yet the Cachet itself is saying no update since I started the plugin yesterday

![screen shot 2017-08-03 at 11 12 29](https://user-images.githubusercontent.com/18073067/28917197-b796a6a4-783c-11e7-9916-807c382da95b.png)

Second issue:
I triggered the even on my IT services  for testing purposes - The Test1 is pinging the website every 60 sec and return 200 OK, if not available it returns 400 
And I am getting this error

```bash
Aug  3 09:52:37 localhost python: 2017-08-03 09:52:37 UTC ERROR: (Trigger Watcher) ClientHttpError[https://status.sonru.com/api/v1/incidents, 400: {"errors":[{"id":"261aa814-c094-4550-acb9-107f4969d82c","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The notify field must be true or false."]}}]}]
```

**Comment by nopp** [comment]
I have the same problem here.

**Comment by qk4l** [comment]
> Yet the Cachet itself is saying no update since I started the plugin yesterday

It's actually not the best description. There is not any components`s property that you could update except its status. So this timestamp shows the last change of component state not more.

> And I am getting this error
> "meta":{"details":["The notify field must be true or false."]}}]}]

It's look like a bug in Cachet. Because this field is optional. Try to use stable version for example 2.3.14.

**Comment by nan008** [comment]
On the first issue - is there anything to be done by zabbix-cachet or should I go and bug the Cachet guys? Ideally for me it should say last checked/updated and the updated timestamp - at the moment for me it looks like the last time the status was updated/checked from Zabbix was 2nd of August.

Second issue - I downgraded to 2.13.14 and I can confirm that the trigger is correctly passed now

![screen shot 2017-08-09 at 10 35 54](https://user-images.githubusercontent.com/18073067/29115176-90c7f0f8-7cee-11e7-8edc-9582e0e0bbf9.png)

There is a bug open for 2.4 and I added my comment to this conversation.

Thanks for help

**Comment by qk4l** [comment]
> There is a bug open for 2.4 and I added my comment to this conversation.

Thank you for this.

> Waited 20 minutes, nothing happened. 
Check you _update_comp_interval_ setting. 

> On the first issue - is there anything to be done by zabbix-cachet or should I go and bug the Cachet guys? 
Nope I can't do anything with this. :( 
It's not a bug. May be Cachet guys wants to save last time of component's status change. But I agree that "Last updated" is not good description for that.

**Comment by nan008** [comment]
I will let you know if they fixed the bug in 2.4
I will go and annoy the Cachet guys now about the Last updated status as for me it looks like the status was not checked since Wed 2nd of August
Thnks for all your help

**Comment by nan008** [comment]
Hi @qk4l 
as you know I opened the bug report with Cachet quoting your answer to me on this ticket

For this line:

> It's look like a bug in Cachet. Because this field is optional. Try to use stable version for example 2.3.14.


He asked:
> Which field is now optional, sorry?

Can you answer him?

**Comment by qk4l** [comment]
> "meta":{"details":["The notify field must be true or false."]}}]}]
Notify field in Post request to _api/v1/incidents_

**Comment by nan008** [comment]
jbrooksuk commented 2 hours ago (Owner of Cachet)

> Ah right. You need to send notify=0 or notify=1.
> Odd. We have a default of true for notifications. Make sure that the package is sending a 1 or 0 is all I can say for now.
