### ISSUE TITLE
Change service statuses when zabbix is unavailable

### ISSUE THREAD

**Issue by martivo** [qk4l/zabbix-cachet#20]
Hi,
Is there anything we can do to detect issues with zabbix itself? During large outages also zabbix itself can be affected and currently it will not reflect on Components of Cachet.

Maybe have the possibility to have a component in cachet called "Zabbix" or similar as an optional configuration? That will be marked down when there is issue with reaching zabbix for this plugin itself.

When I on purpose disrupt reaching of zabbix - then in the log I see:
`Aug  8 08:01:07 ip-172-31-19-171 zabbix-cachet[22872]: 2017-08-08 08:01:07 UTC INFO: (Trigger Watcher) Resetting dropped connection: [hostname redacted]`

So the plugin is aware of the connection breaking to zabbix, but it is not reflected in the components.

As a workaround we could create a separate monitor into Cachet itself to monitor zabbix, but it would be nicer if this zabbix-cachet itself is able to report zabbix issues.

**Comment by qk4l** [comment]
Hi,

It's not the zabbix-cachet business (as sync process) to control if Zabbix or Cachet is available.
The right way is to configure HA for Zabbix Web and Cachet but for sure that may be a difficult or even overhead for small installations.

Actually I liked your idea and if I have the time or someone will create a PR, I will be happy to make a merge.

**Comment by mardicas** [comment]
I'll see if I have time to write that feature myself - at the moment no spare time for it. When I do, Ill be sure to send the code changes.

I think we all know HA is never 100% - so I would still want this feature with or without HA.
