### ISSUE TITLE
Initial error message replaced by ack

### ISSUE THREAD

**Issue by pasterntt** [qk4l/zabbix-cachet#23]
Hello,

I just started to use your docker container and have a major "issue", where I'm not sure wether its wanted or not.

If I kill zabbix-agent on a monitored host, everything's okay. A report is created and displayed in Cachet but once I ack it, the initial report is completely replaced by by the ack message. If I then resume the zabbix-agent, a "Resolved" is appended to the ack.

Log lines, which are relevant:

`2017-09-16 19:49:21  INFO: (MainThread) Component *.*.*.lio-server.de was created in group id 4.
2017-09-16 19:49:21  INFO: (MainThread) Component *.*.*.lio-server.de was created in group id 0.
2017-09-16 19:49:21  INFO: (MainThread) Successfully synced Cachet components with Zabbix Services
`
It can be seen [here](http://status.lio-server.de), what I mean (Check the 16th of September)

**Comment by qk4l** [comment]
Hello,

It's working as expected.
The idea is that initial message which is creating based on trigger description or item name generally not  good enough to describe a problem.

So when human make a acknowledge, he can write it in human way and provide good explanation for status page visitors.
