### ISSUE TITLE
The description field is required. Cachet 2.4

### ISSUE THREAD

**Issue by wesleyhuang** [qk4l/zabbix-cachet#24]
With Cachet 2.4.0DEV, the POST to Cachet on new components failed with HTTP return code 400: "The description field is required" 

ERROR: (MainThread) ClientHttpError[https://xxxxxxxxx/api/v1/components, 400: {"errors":[{"id":"xxxxxxxxxxxx","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The name field is required.","The description field is required."]}}]}]

As a work-around, I change line #237 to params = {'name': name, 'link': '', 'description': name, 'status': '1', 'group_id': 0}

**Comment by qk4l** [comment]
Hi,

1. _description_ param is not marked as required in [(https://docs.cachethq.io/reference#components)](docs). May be it's a bug and Cachet developers will fixed it.
2. When zabbix-cachet creates components it try to fill _description_ param based on Zabbix Trigger description which linked to IT Service. In other case an empty string is used.

Try to add description to your trigger. It should fixed a problem.

**Comment by qk4l** [comment]
Although Cachet 2.4 have not released and I can not test it (docker image is absent) I think it fixed 1.3.6
