### ISSUE TITLE
Docker running error - Invalid format

### ISSUE THREAD

**Issue by kodesmon** [qk4l/zabbix-cachet#29]
Hi,

I'm getting this error when I try to create a container 

ClientHttpError[http://192.168.56.102:8000/api/v1/components, 400: {"errors":[{"id":"943625b1-258a-41fb-aa7b-6cf29bff87fc","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["The link format is invalid."]}}]}]
2017-12-25 18:52:33  ERROR: (MainThread) 'NoneType' object is not subscriptable

Please help! this is my command

sudo docker run --name zabbix-cachet -v zabbix-cachet.yml:/config.yml qk4l/zabbix-cachet

and this is my config.yml 

zabbix:
  user: admin
  pass: zabbix
  server: http://192.168.56.102
  https-verify: false

cachet:
  token: xxxxxxxxxxxxxxx
  server: http://192.168.56.102:8000
  https-verify: false

settings:
  root_service: Cachet

**Comment by qk4l** [comment]
Hi,

Check your Zabbix`s triggers which is used in zabbix-cachet synchronization.
It seems that at least one of them has invalid URL field.

Clear it or put valid hyperlink there.

**Comment by kodesmon** [comment]
Certainly worked! Many thanks!
