### ISSUE TITLE
Trigger Not Updating Cachet

### ISSUE THREAD

**Issue by apssupport** [qk4l/zabbix-cachet#3]
Good morning,

New issue now. The triggers are not reflecting on cachet. The only thing replicating from zabbix to cachet are the groups and components.

![image](https://cloud.githubusercontent.com/assets/19654323/17704500/3645bb52-63a3-11e6-83f0-98a94cd57ed5.png)

![image](https://cloud.githubusercontent.com/assets/19654323/17704543/55420d4e-63a3-11e6-9dff-d4a7f39ffb4d.png)

**Comment by qk4l** [comment]
Hello, sorry for delay.

Do you use the last version? Please upgrade if not. There was a issue when only one component per group was updated.

Unfortunately screen shots do not have enough information for debugging. Could  you please attach logs so I can see what going on.

Thank you!

**Comment by apssupport** [comment]
Hi Artem,

I am running the latest version after you recommended to install it due to
only one component being updated. I will send you the logs tonight. Thank
you so much for your help.

**Comment by apssupport** [comment]
Do you know where I can find the log for this script?

**Comment by qk4l** [comment]
Script just generate output logs.
Based on this https://github.com/qk4l/zabbix-cachet/issues/2#issuecomment-239954720  you seems use incorrect python version. Which one do you have?
Have you tried to use [Docker installation](https://github.com/qk4l/zabbix-cachet#docker-installation) ?

**Comment by apssupport** [comment]
Hi,

I have python 2.7.6 installed on the server. Do you recommend I upgrade? I haven't tried the docker install yet, do you think it might help?

Thank you,

Evangelos

**Comment by apssupport** [comment]
Actually, I have a higher version installed.

arhigos@status:/$ python -V
Python 2.7.6
arhigos@status:/$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by qk4l** [comment]
This script required python 3. It's the reason why triggers does not updates.
Docker installation is pretty easy and contained all required libs for work.

**Comment by apssupport** [comment]
Thank you, I will try the docker install version. Should I remove the current one I have installed/running?

**Comment by qk4l** [comment]
> Should I remove the current one I have installed/running?
Up to you. I preferred to delete not using files. ))

**Comment by apssupport** [comment]
Same here :))

**Comment by apssupport** [comment]
I tried the docker run, how do I know if it is running. After the pull completed, the cursor is frozen and am not sure if I have to exit out or something else. This is the first time I am running docker. Here is what I see:

arhigos@status:/# sudo nano /etc/zabbix-cachet.yml
arhigos@status:/# docker run --name zabbix-cachet -v /etc/zabbix-cachet.yml:/config                         .yml qk4l/zabbix-cachet
Unable to find image 'qk4l/zabbix-cachet:latest' locally
latest: Pulling from qk4l/zabbix-cachet
9b7301678506: Pull complete
06984fada629: Pull complete
cbd9326b4af3: Pull complete
3cf50e26062b: Pull complete
e48aee5d057b: Pull complete
44fd1ef95c7c: Pull complete
260a64c196a9: Pull complete
514f6ecc5ad5: Pull complete
45aa0f467a3e: Pull complete
47488c854ae4: Pull complete
4fd994e9dd72: Pull complete
0e4ab4845759: Pull complete
9532d732dd2f: Pull complete
5d6de710e2c9: Pull complete
63411e32f5e0: Pull complete
5f070e0ba1bf: Pull complete
Digest: sha256:a533f7cfc4f510272398589e991e6c8b1f63b09008c12ae377db278c0c3ab050
Status: Downloaded newer image for qk4l/zabbix-cachet:latest
2016-08-18 17:29:47  INFO: (MainThread) Zabbix Cachet v.0.1 started
2016-08-18 17:29:47  INFO: (MainThread) JSON-RPC Server Endpoint: http://zabbix.                         pqus.com/zabbix/api_jsonrpc.php
2016-08-18 17:29:48  INFO: (MainThread) Restart triggers_watcher worker
2016-08-18 17:29:48  INFO: (Trigger Watcher) start trigger watcher

**Comment by apssupport** [comment]
Got docker to work, and was able to test it. Everything works perfectly! Thank you so much for your help and for this great tool! Issue can be closed.

**Comment by qk4l** [comment]
Happy to read that!
