### ISSUE TITLE
ZAbbix-cachet status shows   ERROR: (MainThread) Expecting value: line 1 column 1 (char 0

### ISSUE THREAD

**Issue by arislanIOT** [qk4l/zabbix-cachet#49]
Installed 
Zabbix server 3.4
Cachet 2.3.9
Zabbix-cachet tried three methods 
When i start the service i get the following error:

root@ip-172-31-29-168:/var/www/html/cachet# /usr/bin/zabbix-cachet restart
2019-03-21 09:57:35 UTC INFO: (MainThread) Zabbix Cachet v.1.3.6 started
2019-03-21 09:57:35 UTC INFO: (MainThread) JSON-RPC Server Endpoint: http://54.171.249.134/zabbix/api_jsonrpc.php
2019-03-21 09:57:35 UTC ERROR: (MainThread) Expecting value: line 1 column 1 (char 0)

Could you please guide me on this

**Comment by qk4l** [comment]
Hi, 
Please enable DEBUG  logging and provide it.

**Comment by arislankareem** [comment]
If you don't mind could you please let me know where i should do it

**Comment by arislankareem** [comment]
Error changed to the following.:

Mar 21 13:17:04 ip-172-31-29-168 systemd[1]: Started Zabbix-Cachet.
Mar 21 13:17:04 ip-172-31-29-168 zabbix-cachet[31681]: 2019-03-21 13:17:04 UTC INFO: (MainThread) Zabbix Cachet v.1.3.6 started
Mar 21 13:17:04 ip-172-31-29-168 zabbix-cachet[31681]: 2019-03-21 13:17:04 UTC INFO: (MainThread) JSON-RPC Server Endpoint: http://54.171.249.134:10051/api_jsonrpc.php
Mar 21 13:17:04 ip-172-31-29-168 zabbix-cachet[31681]: 2019-03-21 13:17:04 UTC ERROR: (MainThread) ('Connection aborted.', BadStatusLine('OK',))
Mar 21 13:17:04 ip-172-31-29-168 systemd[1]: zabbix-cachet.service: Main process exited, code=exited, status=1/FAILURE
Mar 21 13:17:04 ip-172-31-29-168 systemd[1]: zabbix-cachet.service: Unit entered failed state.
Mar 21 13:17:04 ip-172-31-29-168 systemd[1]: zabbix-cachet.service: Failed with result 'exit-code'.

**Comment by qk4l** [comment]
> If you don't mind could you please let me know where i should do it

In config file set 
```
  log_level: DEBUG
  log_level_requests: INFO
```

**Comment by arislankareem** [comment]
The issue is resolved. The api  key settings were wrong. 
thank you
