### ISSUE TITLE
Timezone using local set timezone

### ISSUE THREAD

**Issue by DP19** [qk4l/zabbix-cachet#56]
This is great when it's running on the same server as cachet but not so great when it's running in a container in Kubernetes where cachet is. All of the messages for incidents are in UTC but the zabbix events are in local time and cachet is setup to also be in local time (EDT in this case)

Can we work on getting support for setting this timezone so it will work in k8s correctly?

**Comment by qk4l** [comment]
Do you use qk4l/zabbix-cachet docker image?

May be is better to change TZ in container?
* No code change
* Timezone for logs
* No new config options

**Comment by DP19** [comment]
@qk4l I do use that image and i could mount the correct tzinfo file into the container to /etc/localtime but this is an anti-pattern in k8s where everything is in UTC.

I think this could still be useful for some edge cases where you're running this script for a country/worldwide app and wanting to have 1 main cachet page and a lot of zabbix instances that are local to edge site a person has. You could then set this in config rather than relying on the local timezone of the instance this script is running on.

I think even adding in a template option that adds in the timezone used in the script to the template may help to reduce confusion here instead of having have this new feature.

Another option would be to use cachet's setting for timezone and also localize incidents to that timezone (though I don't see that available in their api docs)
