### ISSUE TITLE
Error Connecting zabbix with cachet

### ISSUE THREAD

**Issue by Mittin-Singh** [qk4l/zabbix-cachet#61]
I have zabbix server hosted on AWS EC2 instance, same for cachet as well. I ran the docker container for zabbix-cachet, and configured the host. Can you help me integrate zabbix with cachet

2020-05-25 18:29:30  INFO: (MainThread) Zabbix Cachet v.1.3.6 started
2020-05-25 18:29:30  INFO: (MainThread) JSON-RPC Server Endpoint: http://10.197.14.232/zabbix/index.php/api_jsonrpc.php
2020-05-25 18:29:30  ERROR: (MainThread) Unable to parse json: <!DOCTYPE html>
<html>
        <head>
                <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta name="Author" content="Zabbix SIA" />
                <title>Warning [refreshed every 30 sec.]</title>
                <link rel="icon" href="favicon.ico">
                <link rel="apple-touch-icon-precomposed" sizes="76x76" href="img/apple-touch-icon-76x76-precomposed.png">
                <link rel="apple-touch-icon-precomposed" sizes="120x120" href="img/apple-touch-icon-120x120-precomposed.png">
                <link rel="apple-touch-icon-precomposed" sizes="152x152" href="img/apple-touch-icon-152x152-precomposed.png">
                <link rel="apple-touch-icon-precomposed" sizes="180x180" href="img/apple-touch-icon-180x180-precomposed.png">
                <link rel="icon" sizes="192x192" href="img/touch-icon-192x192.png">
                <meta name="csrf-token" content=""/>
                <meta name="msapplication-TileImage" content="img/ms-tile-144x144.png">
                <meta name="msapplication-TileColor" content="#d40000">
                <meta name="msapplication-config" content="none"/>
<link rel="stylesheet" type="text/css" href="styles/blue-theme.css" />
</head>
<body lang="en"><main><output class="msg-bad msg-global">Access denied<div class="msg-details"><ul class="msg-details-border"><li>You are logged in as &quot;guest&quot;. You have no permissions to access this page.</li><li>If you think this message is wrong, please consult your administrators about getting the necessary permissions.</li></ul></div><div class="msg-buttons"><button type="button" id="login" name="login" onclick="javascript: document.location = &quot;index.php?request=index.php&quot;;">Login</button><button type="button" id="back" name="back" onclick="javascript: document.location = &quot;zabbix.php?action=dashboard.view&quot;">Go to dashboard</button></div></output></main><script type="text/javascript">
setTimeout('document.location.reload();', 30000);
</script></body></html>

**Comment by Mittin-Singh** [comment]
Now i am getting this error

2020-05-25 18:54:53  INFO: (MainThread) Zabbix Cachet v.1.3.6 started
2020-05-25 18:54:53  INFO: (MainThread) JSON-RPC Server Endpoint: http://10.197.14.232/zabbix/api_jsonrpc.php
2020-05-25 18:54:53  ERROR: (MainThread) ClientHttpError[http://127.0.0.1:8001/api/v1/version, None: HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /api/v1/version (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f5616afb780>: Failed to establish a new connection: [Errno 111] Connection refused',))]
2020-05-25 18:54:53  ERROR: (MainThread) exceptions must derive from BaseException

**Comment by qk4l** [comment]
Hi, did you managed a problem?

```
Failed to establish a new connection: [Errno 111] Connection refused',))]
```
This error means that zabbix-cachet could not reached Cached by follow address - `http://127.0.0.1:8001/api/v1/version`
This is configured in follow config section
```
cachet:
  server: https://cachet.example.com
```
