### ISSUE TITLE
Unable to acknowledge a issue

### ISSUE THREAD

**Issue by danielduchon** [qk4l/zabbix-cachet#62]
After creating a acknowledgment, I get the following error-message in log:
```
Jun 28 11:47:26 vm-zabbix-115 zabbix-cachet[526]: 2020-06-28 11:47:26 CEST ERROR: (Trigger Watcher) triggers_watcher() raised an Exception. Something gone wrong
Jun 28 11:47:26 vm-zabbix-115 zabbix-cachet[526]: 2020-06-28 11:47:26 CEST ERROR: (Trigger Watcher) 'name'
Jun 28 11:47:26 vm-zabbix-115 zabbix-cachet[526]: Traceback (most recent call last):
Jun 28 11:47:26 vm-zabbix-115 zabbix-cachet[526]:   File "/usr/bin/zabbix-cachet", line 611, in triggers_watcher_worker
Jun 28 11:47:26 vm-zabbix-115 zabbix-cachet[526]:     triggers_watcher(service_map)
Jun 28 11:47:26 vm-zabbix-115 zabbix-cachet[526]:   File "/usr/bin/zabbix-cachet", line 539, in triggers_watcher
Jun 28 11:47:26 vm-zabbix-115 zabbix-cachet[526]:     author=msg['name'] + ' ' + msg['surname']
Jun 28 11:47:26 vm-zabbix-115 zabbix-cachet[526]: KeyError: 'name'
```

I'm running ubuntu 18.04 and installed Zabbix-cachet with ppa
everything is up to date

**Comment by qk4l** [comment]
Hi,

I suggest that Zabbix user which is used for acknowledgment does not have 'Name' in hit profile.

Add Name/Surname for all Zabbix users to avoid this error.

Thanks for report.

**Comment by danielduchon** [comment]
Thanks for your reply.

I've double-checked every user.
All fields are filled and the user who as acknowledged, is admin.
Could it be, because the users are connecting via ldap?

How can I help you to debug this?

**Comment by qk4l** [comment]
I've not found problem with LDAP backend but caught (one time) when Zabbix did not return name/surname in acknowledge message.

Please try 1.3.7 version which is tolerant to this.
