### ISSUE TITLE
Support Zabbix 5.X

### ISSUE THREAD

**Issue by fauust** [qk4l/zabbix-cachet#66]
Hi!
Is there any plan to support Zabbix 5.X versions (maybe it's already the case?).

Also, FYI, it seems that Cachet is now actively maintained on this fork https://github.com/fiveai/Cachet/ and so, I am not sure if zabbix-cachet could work with new releases from that fork?

Cheers!

**Comment by dR3b** [comment]
I think there were no API changes in Zabbix or Cachet, so everything works as it should. A quick test confirms that:
```bash
CET INFO: (MainThread) Zabbix ver: 5.0.9. Cachet ver: 2.5.0
CET INFO: (MainThread) Successfully synced Cachet components with Zabbix Services
```

**Comment by fauust** [comment]
Indeed and I can confirm that it works perfectly with the new fork and 2.5 version (and also Zabbix 5.2 versions).

**Comment by qk4l** [comment]
Thanks for testing guys!
