### ISSUE TITLE
Cachet not changing status on alert trigger

### ISSUE THREAD

**Issue by FlanniganColum** [qk4l/zabbix-cachet#70]
I have configured Cachet using docker for a test, and the plugin is configured and works for services detection and creation, however when i trigger a failure my Zabbix Services gets updated fine but the data does not seem to replicate to cachet. 

I have restarted everything and yet still nothing, is there a specific layout and settings needed Zabbix services for this to work?? I know i am using the dev version of cachet, i will try a more GA release but again its just a test of the application so was going to use the latest one in GIT repo..

Zabbix Cachet v.1.3.7
Cachet Version: 2.4.0-dev
Zabbix Version: 5.4.12

**Comment by FlanniganColum** [comment]
I am not a python expert, but i am looking at the code and it looks like you are trying to get the triggerid from the dependencies of the service within the zabbix api.. From the documentation within 5.4 dependencies does not contain this information.. 

is there only specific zabbix versions this plugin works on?

**Comment by mukhinsumojo** [comment]
Anyone have a solution?
I see the same issue.
Services in Zabbix have no trigger independencies, only tags. And service status in cachet is not changing

**Comment by qk4l** [comment]
Script is support Zabbix 2.2 - 7.0. Please update zabbix cachet to 2.1+
